measurement_type: 'diodeIV'
sample:
  type: 'diode' 
  id: '1337420'  #TODO:: this should always be requested from the cli
  preexisting_dose: 0       

  
devices:
  sourcemeter_1:
    model: 'ke2410'  
    address: 25
    lim_cur: 1.0e-3    # compliance in [A]

  picoammeter_1:
    model: 'ke6487'
    address: 15

  picoammeter_2:
    model: 'ke6487'
    address: 23


measurements:
  IV:
    measurement_range:
      v_start: -0.5
      v_end: 0.5
      step_size: 0.1
    bias_range:
      v_start: 0  
      v_end: -400
      step_size: -50
    delay: 3  # delay between setting voltage and executing measurement in [s]
    sample_size: 20  # number of measurements per bias voltage (equal for each picoammeter)
