measurement_type: 'gcdmos'
sample:
  type: 'gcdmos' #TODO: this can always be inferred from which type of measurement is specified (except when executing diode as strip i guess?)
  id: 1337420  #TODO:: this should always be requested from the cli
  preirradiated: true
  current_dose: 3        # this is only used if no dose is provided by the runner (when running msr without obelix)


devices:
  sourcemeter_1:
    model: 'ke2410'  
    address: 8
    lim_cur: 1.0e-3 # compliance current in [A]

  sourcemeter_2:
    model: 'ke2410'  
    address: 25
    lim_cur: 1.0e-3 # compliance current in [A]
    
  switch:           #if the switch is specified, it will try to initialize and use it. if directly connecting to devices, comment switch out.
    model: 'ke7001'
    address: 7
    connections:
      lcrmeter: 3
      picoammeter: 9

  lcrmeter:
    model: 'agilent_4263b'
    address: 17

  picoammeter:
    model: 'ke6487'
    address: 15
    lim_cur: 100.0e-9    # compliance in [A] for the GCD, this should be 10 nA


measurements: 
  testset: [moshalf, mos2000, gcd]    #determines which measurements are exectued
  CV:
    range:
      v_start: 0.   #  -50 if '120um' in self.id else -100
      v_end: -10   #   -400 if '120um' in self.id else (-600 if '200um' in self.id else -900)
      step_size: -5
    sample_size: 5
    lcr_amplitude: 0.250 # 0.501 # ac voltage amplitude in [mV]
    lcr_frequency: 10000  # ac voltage frequency in [Hz]
    delay: 0.3 # delay in [s] between setting the voltage and executing the measurement

  IV:
    range:
      v_start: 10
      v_end: -10
      step_size: -5
    sample_size: 30
    gcd_diode_bias: 10.0  # [V] bias voltage applied to the GCD diode
    delay: 2.0 # delay in [s] between setting the voltage and executing the measurement