measurement_type: 'gcdmos'
sample:
  type: 'gcdmos' #TODO: this can always be inferred from which type of measurement is specified (except when executing diode as strip i guess?)
  id: 100410  #TODO:: this should always be requested from the cli
  preirradiated: true
  current_dose: 0        # this is only used if no dose is provided by the runner (when running msr without obelix)


devices:
  sourcemeter_1:
    model: 'ke2410'  
    address: 8
    lim_cur: 1.0e-3 # compliance current in [A]

  sourcemeter_2:
    model: 'ke2410'  
    address: 25
    lim_cur: 1.0e-3 # compliance current in [A]
    
  switch:           #if the switch is specified, it will try to initialize and use it. if directly connecting to devices, comment switch out.
    model: 'ke7001'
    address: 7
    connections:
      lcrmeter: 3
      picoammeter: 9

  lcrmeter:
    model: 'agilent_4263b'
    address: 17

  picoammeter:
    model: 'ke6487'
    address: 15
    lim_cur: 100.0e-9    # compliance in [A] for the GCD, this should be 10 nA

  multimeter:
    model: 'ke2001'
    address: 16
    sensor_r0: 1000

measurements: 
  testset: [moshalf, mos2000, gcd]    #determines which measurements are exectued
  CV:
    range:
      v_start: 0.   #  -50 if '120um' in self.id else -100
      v_end: -5   #   -400 if '120um' in self.id else (-600 if '200um' in self.id else -900)
      step_size: -0.1
    sample_size: 10
    lcr_amplitude: 0.250 # 0.501 # ac voltage amplitude in [mV]
    lcr_frequency: 10000  # ac voltage frequency in [Hz]
    delay: 0.3 # delay in [s] between setting the voltage and executing the measurement

  IV:
    measurement_range:
      v_start: -0.5
      v_end: 0.5
      step_size: 0.1
    bias_range:
      v_start: 0
      v_end: -20
      step_size: -10
    delay: 3  # delay between setting voltage and executing measurement in [s]
    sample_size: 10  # number of measurements per bias voltage (equal for each picoammeter)

# irradiation:
#   doselist: [0,1,2,5,10]
#   dose_rate: 14.257  ## value taken on Aug 31st 2023
#   voltage: 40  # the voltage of the tube in kV
#   current: 50  # the current of the tube in mA
#   biasing: false  # whether to bias the sample during irradiation

temperature_management:
  chiller:
    enabled: true
    model: 'chiller_cc_505'
    port: 'COM11'
    default_temperature: -25 # this temp is what is used to setup the chiller, 
    update_frequency: 2 #how often the temp manager checks the setpoint updates from the runner. 

  logging:
    directory: 'temperature_logs' # Directory to save log files
    log_interval_sec: 20          # How often to write to the log file (in seconds)
  plotting:
    update_interval_sec: 2 # plotting update frequency in seconds

# annealing:
#   n_iterations: 10
#   period: 1  # time in [m] between measurements
#   anneal_temp: 30
#   measur_temp: 10
