measurement_type: 'strip'
sample:
  type: 'strip'
  id: '1337420'  #TODO:: this should always be requested from the cli
  preexisting_dose: 0      


devices:
  sourcemeter_1:
    model: 'ke2410'  
    address: 8
    lim_cur: 1.0e-3

  sourcemeter_2:
    model: 'ke2410'  
    address: 25
    lim_cur: 1.0e-3
    
  switch:
    model: 'ke7001'
    address: 7
    connections:
      lcrmeter: 1
      picoammeter: 3

  lcrmeter:
    model: 'agilent_4263b'
    address: 17

  picoammeter:
    model: 'ke6487'
    address: 15


measurements:
  CV:
    range:
      v_start: -100   #  -50 if '120um' in self.id else -100
      v_end: -600   #   -400 if '120um' in self.id else (-600 if '200um' in self.id else -900)
      step_size: -20
    sample_size: 10
    lcr_amplitude: 0.5
    frequencies: [100, 1000, 10000]  # needs to be integers otherwise the plotting utils complain
    measurement_delay: 5 # delay after setting the voltage before starting the measurement
    trig_delay: 0  # delay between lcr triggers
    
  IV:
    measurement_range:
      v_start: -1
      v_end: 1
      step_size: 0.2
    bias_range:
      v_start: -100
      v_end: -300
      step_size: -25
    sample_size: 10 # default = 10
    bias_delay: 5  # delay in ivscan after stting the bias voltage
    step_delay: 1 # delay in the ivpoint after setting the measurement voltage

