devices:
  sourcemeter_1:
    model: 'ke2410'  
    address: 8
    open_short_correction: false
    correction_count: 5
    lim_cur: 1.0e-3

  sourcemeter_2:
    model: 'ke2410'  
    address: 25
    lim_cur: 1.0e-3
    
  switch:
    model: 'ke7001'
    address: 7
    # connections:
    #   lcrmeter: 1
    #   picoammeter: 3

  lcrmeter:
    model: 'agilent_4263b'
    address: 17

  picoammeter:
    model: 'ke6487'
    address: 15

measurements:
  CV:
    range:
      v_start: -100   #  -50 if '120um' in self.id else -100
      v_end: -600   #   -400 if '120um' in self.id else (-600 if '200um' in self.id else -900)
      step_size: -50
    sample_size: 20
    lcr_amplitude: 0.5
    frequencies: [10000, 100000]  # needs to be integers otherwise the plotting utils complain
    delay: 5
  IV:
    measurement_range:
      v_start: -1
      v_end: 1
      step_size: 0.2
    bias_range:
      v_start: -100
      v_end: -400
      step_size: -50
    sample_size: 10 # default = 10
    delay: 5
    step_delay: 5
