sensorName: 'N4793_B ' #TODO: sensorName should be provided when invoking the test, to avoid duplication
irradiationSteps: [0,0.5,1,2,3,4,5,7,10,15,20] # [0,5,10,15,20,30,50,70,100,150,200] #,300,500,700,1000,1500]
voltage_settings:

#TODO: naming convention should always enforce numbering of devices, even when there is only one device of some type.
#TODO: remove unused variables, and move generic variables outside of devices section
#TODO: make names consistent accross files, all snake_case 
devices:
  sourcemeter_1:
    model: 'ke2410'  
    address: 25
    open_short_correction: false
    correction_count: 5
    range:
      Vmin: -800  #TODO: make names consistent with other config files
      Vmax: -10
      Vstep: -10
    range_iv:
      Vmin_iv: -0.5
      Vmax_iv: 0.5
      Vstep_iv: 0.1
    n_sampling: 100 
    delay_vol: 10  # VERY INCONSISTENT NAMING TOGETHER WITH KEITHLEY FUNCITONS delay between SETTING voltage and executing measurement in [s]
    delay_ramp: 1 # 
    volt_list_test: [-5, -10, -15, -30, -40, -60, -90, -110, -130, -160, -180, -200, -280, -300, -350, -400, -450, -500, -600, -800]  # [ -145, -155, -165, -175, -185, -195 ]  # [-150]
    lim_cur: 1.0e-3    # compliance in [A]
    lim_vol: 10      # compliance in [V]

  sourcemeter_2:
    model: 'ke2410'  
    address: 8
    open_short_correction: false
    correction_count: 5
    range:
      Vmin: -800  #TODO: make names consistent with other config files
      Vmax: -10
      Vstep: -10
    range_iv:
      Vmin_iv: -0.5
      Vmax_iv: 0.5
      Vstep_iv: 0.1
    n_sampling: 100 
    delay_vol: 10  # VERY INCONSISTENT NAMING TOGETHER WITH KEITHLEY FUNCITONS delay between SETTING voltage and executing measurement in [s]
    delay_ramp: 1 # 
    volt_list_test: [-5, -10, -15, -30, -40, -60, -90, -110, -130, -160, -180, -200, -280, -300, -350, -400, -450, -500, -600, -800]  # [ -145, -155, -165, -175, -185, -195 ]  # [-150]
    lim_cur: 1.0e-3    # compliance in [A]
    lim_vol: 10      # compliance in [V]    
    
  picoammeter:
    model: 'ke6487'
    address: 15
    # lim_cur: 5.0e-7  # compliance in [A] for the GCD, this should be ?
    n_sampling: 30